#!/bin/bash

# This stub replaces the all too smart script from the rpm suite,
# which puts each and every perl module it finds in polymake
# on the RPM package's Provides: list.

# If we export shared libraries some day, we have to start the real
# find-provides and filter its output.

while read dummy; do :; done
exit 0
